const app=document.getElementById('app');
const faces={Kid:['🧒','👧','🧑','👦','👩‍🦱','👨‍🦱','👩','👨','🧑‍🦰','🧑‍🦱'],Man:['👨🏻','👨🏼','👨🏽','👨🏾','👨🏿','👨‍🦰','👨‍🦱','👨‍🦲','🧔🏻','🧔🏽'],Woman:['👩🏻','👩🏼','👩🏽','👩🏾','👩🏿','👩‍🦰','👩‍🦱','👩‍🦳','👩🏻‍🦱','👩🏽‍🦰'],'Old Man':['👴🏻','👴🏼','👴🏽','👴🏾','👴🏿','👨🏻‍🦳','👨🏼‍🦳','🧓🏻','🧓🏽','🧓🏿'],'Old Woman':['👵🏻','👵🏼','👵🏽','👵🏾','👵🏿','👩🏻‍🦳','👩🏼‍🦳','👩🏽‍🦳','🧓🏻','🧓🏽']};
let sess=localStorage.getItem('spy-last-four-session')||'', roomCode=localStorage.getItem('spy-last-four-room')||'', state=null, es=null, selectedTarget='', selectedQuestion='', alertText='', timerTick=null, chosen=null;
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const face=a=>faces[a?.category]?.[Math.max(0,parseInt(a?.variant||'01',10)-1)%10]||'🧑';
async function api(url,data,session=sess){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-Session':session},body:JSON.stringify(data)});const j=await r.json();if(!r.ok)throw Error(j.error||'Something went wrong');return j;}
function remember(code,id){sess=id;roomCode=code;localStorage.setItem('spy-last-four-session',id);localStorage.setItem('spy-last-four-room',code);}
function goLobby(){state=null;roomCode='';sess='';localStorage.removeItem('spy-last-four-room');localStorage.removeItem('spy-last-four-session');if(es)es.close();es=null;render();}
function connect(){if(es)es.close();es=new EventSource(`/api/room/${encodeURIComponent(roomCode)}/events?session=${encodeURIComponent(sess)}`);es.onmessage=e=>{state=JSON.parse(e.data);render();};es.onerror=()=>{if(state){state.players=state.players.map(p=>p.id===state.me?.id?{...p,connected:false}:p);}};}
function header(){return `<header class="brand"><div class="brand-mark">✳ &nbsp; THE HOTEL IS OPEN &nbsp; ✳</div><h1>SPY: LAST FOUR</h1><div class="sub">A game of secrets, suspicion &amp; Room 401</div></header>`;}
function playerCard(p,showRole=false){return `<div class="player"><div class="avatar ${p.active?'':'dead'}">${face(p.avatar)}</div><div style="min-width:0"><div class="pname">${safe(p.name)}${p.isHost?' <span class="pill">HOST</span>':''}</div><div class="pmeta">${p.connected?'IN THE HOTEL':'RECONNECTING'}${!p.active?' · ELIMINATED':''}${showRole&&p.id===state.me?.id?` · ${state.me.role==='spy'?'SPY':'CIVILIAN'}`:''}</div></div></div>`;}
function setAlert(err){alertText=err.message||String(err);render();setTimeout(()=>{alertText='';render();},3500);}
async function act(type,data={}){try{alertText='';const x=await api(`/api/room/${roomCode}/action`,{type,...data});if(x.state){state=x.state;if(type==='avatar')chosen={...state.players.find(p=>p.id===state.me.id).avatar};render();}}catch(e){if(type==='avatar'&&state?.me){chosen={...state.players.find(p=>p.id===state.me.id).avatar};}setAlert(e);}}
function viewHome(){app.innerHTML=`<div class="shell">${header()}<section class="card narrow stack"><div><label class="label" for="name">Your name</label><input class="field" id="name" maxlength="18" placeholder="Name on the guest list" autocomplete="nickname"></div><button class="btn full" id="create">OPEN A NEW ROOM</button><div class="divider"></div><div><label class="label" for="code">Have a room code?</label><div class="row"><input class="field" id="code" maxlength="6" placeholder="ABC123" style="text-transform:uppercase"><button class="btn secondary" id="join">JOIN ROOM</button></div></div><p class="muted small center">Gather 5 or 6 players. No accounts, no downloads — just a room code.</p>${alertText?`<div class="notice error">${safe(alertText)}</div>`:''}</section><div class="copyright">KEEP YOUR STORY STRAIGHT</div></div>`;
document.getElementById('create').onclick=async()=>{try{const name=document.getElementById('name').value;const x=await api('/api/room',{name},'');remember(x.code,x.session);connect();}catch(e){setAlert(e);}};document.getElementById('join').onclick=async()=>{try{const name=document.getElementById('name').value;const code=document.getElementById('code').value.trim().toUpperCase();if(!code)throw Error('Enter a room code');const x=await api(`/api/room/${encodeURIComponent(code)}/join`,{name},'');remember(x.code,x.session);connect();}catch(e){setAlert(e);}};}
function avatarPanel(){const current=chosen||state.players.find(p=>p.id===state.me?.id)?.avatar||{category:'Man',variant:'01'};return `<div class="stack"><div><label class="label">Choose your character</label><div class="avatars">${Object.keys(faces).map(category=>`<button type="button" class="avatar-choice ${current.category===category?'selected':''}" data-cat="${safe(category)}" aria-pressed="${current.category===category}"><span class="face">${faces[category][parseInt(current.variant||'01',10)-1]}</span><span class="cat">${category}</span></button>`).join('')}</div></div><div><label class="label">Variant · ${current.variant}</label><div class="avatars">${faces[current.category].map((f,i)=>`<button type="button" class="avatar-choice ${String(i+1).padStart(2,'0')===current.variant?'selected':''}" data-var="${String(i+1).padStart(2,'0')}" aria-pressed="${String(i+1).padStart(2,'0')===current.variant}"><span class="face">${f}</span><span class="cat">Variant ${i+1}</span></button>`).join('')}</div></div><p class="muted small">Pick a different face from your fellow guests where possible.</p></div>`;}
function viewLobby(){app.innerHTML=`<div class="shell">${header()}<section class="card"><div class="topline"><div><span class="eyebrow">THE GUEST LIST</span><h2 class="section-title">Lobby</h2></div><div class="center"><div class="label">ROOM CODE</div><div class="room-code">${safe(state.code)}</div></div></div><div class="row"><button class="btn secondary" id="copy">COPY INVITE CODE</button><span class="muted small">${state.players.length}/6 guests · need 5 to begin</span></div><div class="players">${state.players.map(p=>playerCard(p)).join('')}</div><div class="divider"></div>${avatarPanel()}<div class="divider"></div><div class="row" style="justify-content:space-between"><button class="btn ghost" id="leave">LEAVE ROOM</button>${state.me.isHost?`<button class="btn" id="start" ${state.players.length<5||state.players.length>6?'disabled':''}>BEGIN THE NIGHT</button>`:`<span class="muted small">Waiting for the host to open the doors…</span>`}</div>${alertText?`<div class="notice error" style="margin-top:14px">${safe(alertText)}</div>`:''}</section><div class="copyright">ROOM 401 · CHECK IN AT YOUR OWN RISK</div></div>`;
document.getElementById('copy').onclick=async()=>{try{await navigator.clipboard.writeText(state.code);document.getElementById('copy').textContent='COPIED';}catch{}};document.getElementById('leave').onclick=()=>act('leave').then(goLobby);document.getElementById('start')?.addEventListener('click',()=>act('start'));document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{const current=chosen||state.players.find(p=>p.id===state.me.id)?.avatar||{variant:'01'};chosen={category:b.dataset.cat,variant:current.variant};render();act('avatar',chosen);});document.querySelectorAll('[data-var]').forEach(b=>b.onclick=()=>{const current=chosen||state.players.find(p=>p.id===state.me.id)?.avatar||{category:'Man'};chosen={category:current.category,variant:b.dataset.var};render();act('avatar',chosen);});}
function timer(){if(!state.timerEndsAt)return'';return `<span class="timer" id="timer">⏱ 00:00</span>`;}
function clock(){const el=document.getElementById('timer');if(!el)return;const n=Math.max(0,Math.ceil((state.timerEndsAt-Date.now())/1000));el.textContent=`⏱ ${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;}
function scene(){const items=state.players.filter(p=>p.active);return `<div class="table-scene ${state.finalFour?'final':''}"><div class="table-center">ROOM 401</div><div class="seats">${items.map((p,i)=>`<div class="seat" style="left:${50+Math.sin(i*2*Math.PI/items.length)*43}%;top:${50-Math.cos(i*2*Math.PI/items.length)*46}%" title="${safe(p.name)}">${face(p.avatar)}</div>`).join('')}</div></div>`;}
function votes(){if(!state.revealedVotes)return'';const counts=state.revealedVotes.counts;return `<div class="vote-result"><span class="label">BALLOT REVEALED · ${state.revealedVotes.ballotCount} VOTES</span>${state.players.filter(p=>p.active||p.id===state.eliminatedId).map(p=>`<div class="barrow"><span>${safe(p.name)}</span><div class="bar"><i style="width:${Math.round((counts[p.id]||0)/Math.max(1,...Object.values(counts))*100)}%"></i></div><b>${counts[p.id]||0}</b></div>`).join('')}</div>`;}
function content(){const me=state.me, phase=state.phase, ownTurn=phase==='question'&&state.currentTurn===me.id, needsAnswer=phase==='answer'&&state.targetId===me.id;
if(phase==='opening')return `<div class="stage cinema"><div><div class="door">✧</div><h2>THE ARRIVAL</h2><p>Six figures approach the hotel through a curtain of rain. One of them has come with a secret.</p></div></div>`;
if(phase==='private')return `<div class="stage cinema"><div><span class="eyebrow">YOUR PRIVATE ROOM</span><h2>YOUR SECRET</h2>${me.role==='spy'?`<div class="role spy">YOU ARE THE SPY</div><p>${safe(me.hint)} Blend in. Listen closely. Find the location.</p>`:`<div class="role">YOU ARE A CIVILIAN</div><p class="loc">${safe(me.location)}</p><p>Keep the location secret. Spot the guest who doesn't belong.</p>`}</div></div>`;
if(phase==='room401')return `<div class="stage cinema ${state.finalFour?'final':''}"><div><span class="eyebrow">THE HOTEL · ${state.finalFour?'FINAL ROUND':'ROUND '+state.round}</span><h2>ROOM 401</h2><p>Take your seat. Watch every face. The questioning begins.</p></div></div>`;
if(phase==='question'||phase==='answer')return `<div class="eyebrow">${state.finalFour?'FINAL FOUR · ONE LAST CHANCE':'ROUND '+state.round+' · QUESTIONING'}</div>${scene()}<div class="grid2"><div class="card" style="padding:16px"><div class="label">CURRENT TURN ${timer()}</div><h3 class="section-title">${safe(state.turnName||'The guests')}</h3>${ownTurn?`<p class="muted small">Choose a guest and ask a question.</p><div class="target-grid">${state.players.filter(p=>p.active&&p.id!==me.id).map(p=>`<button type="button" class="target ${selectedTarget===p.id?'chosen':''}" data-target="${p.id}" aria-pressed="${selectedTarget===p.id}">${face(p.avatar)} ${safe(p.name)}</button>`).join('')}</div><label class="label" style="margin-top:14px">Choose a question</label><div class="stack" style="gap:7px">${state.questions.map(q=>`<button type="button" class="target ${selectedQuestion===q?'chosen':''}" data-question="${safe(q)}" aria-pressed="${selectedQuestion===q}">${safe(q)}</button>`).join('')}</div><button class="btn full" id="ask" style="margin-top:13px" ${!selectedTarget||!selectedQuestion?'disabled':''}>ASK QUESTION</button>`:`<p class="muted small">${phase==='answer'?`${safe(state.announcement)} · waiting for answer…`:'Listen carefully. Your turn is coming.'}</p>`}</div><div class="card" style="padding:16px"><div class="label">${phase==='answer'&&needsAnswer?'YOUR ANSWER':'YOUR ROLE'}</div>${needsAnswer?`<p class="muted small">${safe(state.currentQuestion)}</p><input class="field" id="answer" maxlength="160" placeholder="Answer in a sentence"><button class="btn full" id="submit-answer" style="margin-top:10px">SUBMIT ANSWER</button>`:me.role==='spy'?`<div class="role spy">THE SPY</div><p>${safe(me.hint)}</p>`:`<div class="loc">${safe(me.location)}</div><p class="muted small">Keep it from the Spy.</p>`}</div></div>`;
if(phase==='vote'||phase==='revote')return `<div class="eyebrow">${state.finalFour?'FINAL FOUR':'ROUND '+state.round} · ${phase==='revote'?'REVOTE':'PRIVATE BALLOT'}</div>${scene()}<div class="card narrow"><div class="label">${timer()}</div><h2 class="section-title" style="text-align:center">WHO IS THE SPY?</h2><p class="muted small center">Your vote stays private until all ballots are in. You cannot vote for yourself.</p>${state.revealedVotes?votes():state.me.hasVoted?`<div class="notice">BALLOT SEALED · ${state.votesIn}/${state.eligibleVotes}</div>`:`<div class="target-grid">${state.players.filter(p=>p.active&&p.id!==me.id).map(p=>`<button class="target ${selectedTarget===p.id?'chosen':''}" data-target="${p.id}">${face(p.avatar)} ${safe(p.name)}</button>`).join('')}</div><button class="btn full" id="vote" style="margin-top:14px" disabled>CAST PRIVATE VOTE</button>`}</div>`;
if(phase==='intermission')return `<div class="stage cinema ${state.finalFour?'final':''}"><div><span class="eyebrow">${state.finalFour?'THREE CIVILIANS · ONE SPY':'THE HOTEL HAS MADE ITS CHOICE'}</span><h2>${safe(state.announcement||'WRONG PERSON')}</h2><p>${state.finalFour?'The final four return to the table for one last round.':'The next round begins soon. The Spy is still among you.'}</p>${votes()}</div></div>`;
if(phase==='gameover')return `<div class="stage cinema final"><div><span class="eyebrow">THE NIGHT IS OVER</span><h2>${state.winner==='civilians'?'CIVILIANS WIN':'SPY WINS'}</h2><p>The Spy was <strong>${safe(state.spyName||'')}</strong>.</p><div class="role ${state.winner==='spy'?'spy':''}">${state.winner==='civilians'?'THE HOTEL RELEASES ITS GUESTS':'THE SPY ESCAPES INTO THE NIGHT'}</div></div></div><div class="card narrow" style="margin:auto"><div class="label">FINAL TABLE</div><div class="players">${state.players.map(p=>`<div class="player"><div class="avatar ${p.active?'':'dead'}">${face(p.avatar)}</div><div><div class="pname">${safe(p.name)}</div><div class="pmeta">${p.id===state.winner?'':p.active?'STILL STANDING':'ELIMINATED'} · ${p.id===state.players.find(x=>x.name===state.spyName)?.id?'SPY':p.active||p.id===state.eliminatedId?'CIVILIAN':''}</div></div></div>`).join('')}</div>${votes()}${state.me.isHost?`<button class="btn full" id="replay" style="margin-top:14px">PLAY AGAIN</button>`:''}</div>`;
return `<div class="stage"><div><h2>THE HOTEL IS PREPARING</h2><p>Gathering everyone at Room 401…</p></div></div>`;}
function viewGame(){app.innerHTML=`<div class="shell">${header()}<section class="card"><div class="topline"><div><span class="eyebrow">PRIVATE GAME · ${safe(state.code)}</span><h2 class="section-title">${safe(state.phase==='gameover'?'The Last Guest':state.finalFour?'Final Four':'Room 401')}</h2></div><div class="center"><div class="label">PLAYERS</div><div class="room-code" style="font-size:21px">${state.activeCount} <span class="muted">/ ${state.players.length}</span></div></div></div>${alertText?`<div class="notice error" style="margin-bottom:14px">${safe(alertText)}</div>`:''}<div class="notice ${state.phase==='gameover'?'':'hidden'}">${safe(state.announcement||'')}</div>${content()}<div class="divider"></div><div class="label">GUESTS IN THE HOTEL</div><div class="players">${state.players.map(p=>playerCard(p,true)).join('')}</div><div class="footer"><span class="muted small">${state.me.role==='spy'&&state.phase!=='lobby'?'YOUR SECRET IS YOURS ALONE':'STAY SHARP · TRUST NO ONE'}</span><button class="btn ghost" id="leave">LEAVE GAME</button></div></section><div class="copyright">A ROOM CODE IS ALL YOU NEED TO PLAY AGAIN</div></div>`;
document.querySelectorAll('[data-target]').forEach(b=>b.onclick=()=>{selectedTarget=b.dataset.target;render();});document.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>{selectedQuestion=b.dataset.question;render();});document.getElementById('ask')?.addEventListener('click',()=>act('question',{targetId:selectedTarget,question:selectedQuestion}));document.getElementById('submit-answer')?.addEventListener('click',()=>act('answer',{answer:document.getElementById('answer').value}));document.getElementById('vote')?.addEventListener('click',()=>act('vote',{targetId:selectedTarget}));document.getElementById('replay')?.addEventListener('click',()=>act('replay'));document.getElementById('leave').onclick=()=>act('leave').then(goLobby);if(timerTick)clearInterval(timerTick);timerTick=setInterval(clock,500);clock();}
function render(){if(!state){viewHome();return;}if(state.phase==='lobby'){viewLobby();return;}viewGame();}
async function resume(){if(!sess||!roomCode){render();return;}try{const r=await fetch(`/api/room/${encodeURIComponent(roomCode)}/events?session=${encodeURIComponent(sess)}`);if(!r.ok){goLobby();return;}/* EventSource owns the stream; fetch above is only an auth probe. */await r.body?.cancel();connect();}catch{render();}}
if(sess&&roomCode)resume();else render();
