const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');

const PORT = Number(process.env.PORT || 3000);
const ROOT = __dirname;
const rooms = new Map();
const locations = [
  { place: 'Grand Central Station', hint: 'A bustling transit hub where thousands pass through each day.', qs: ['What sounds would you hear here?', 'What would you bring with you?', 'When is it busiest?', 'What might make you stay longer?'] },
  { place: 'The Aquarium', hint: 'A cool, blue-lit place filled with creatures from the water.', qs: ['What would you see first?', 'What sounds belong here?', 'Who would enjoy visiting?', 'What should you bring?'] },
  { place: 'Mountain Lodge', hint: 'A remote retreat surrounded by peaks and pine trees.', qs: ['What is the best time to visit?', 'What would you pack?', 'What might you do here?', 'What would you hear outside?'] },
  { place: 'Old Movie Theater', hint: 'A dark room where stories flicker across a giant screen.', qs: ['What would you find at the entrance?', 'What makes a visit memorable?', 'What might you smell?', 'Who would come here?'] },
  { place: 'Night Market', hint: 'A lively open-air stretch of stalls after sunset.', qs: ['What would you try first?', 'What time would you arrive?', 'What might you hear?', 'How would you pay?'] },
  { place: 'Botanical Garden', hint: 'A peaceful collection of plants and winding paths.', qs: ['What would you notice first?', 'What should visitors bring?', 'When is it most beautiful?', 'What might you photograph?'] },
  { place: 'Lighthouse', hint: 'A lonely tower guiding travelers through the dark.', qs: ['Who might work here?', 'What can you see from here?', 'What might you hear at night?', 'How would you get here?'] },
  { place: 'Train Dining Car', hint: 'A narrow restaurant that travels across the countryside.', qs: ['What would you order?', 'Where would you sit?', 'What makes it unusual?', 'What would you see outside?'] },
  { place: 'Art Museum', hint: 'A quiet place where people come to look closely.', qs: ['What would you spend time looking at?', 'What should you not do here?', 'Who might you come with?', 'What makes a visit special?'] },
  { place: 'Desert Camp', hint: 'A small shelter beneath an enormous night sky.', qs: ['What would you bring?', 'What would you see at night?', 'What might you hear?', 'When would you wake up?'] }
];
const variants = ['01','02','03','04','05','06','07','08','09','10'];
const timers = new Map();
const rand = n => crypto.randomInt(n);
const token = () => crypto.randomBytes(18).toString('hex');
const code = () => crypto.randomBytes(3).toString('hex').toUpperCase();
const clone = x => JSON.parse(JSON.stringify(x));

function publicState(room, playerId) {
  const players = [...room.players.values()].map(p => ({ id:p.id, name:p.name, avatar:p.avatar, connected:p.connected, active:p.active, isHost:p.id===room.hostId }));
  const you = room.players.get(playerId);
  const me = you ? { id:you.id, isHost:you.id===room.hostId, active:you.active, role: room.phase!=='lobby'&&room.phase!=='opening' ? you.role : undefined, location: you.role==='civilian'&&room.phase!=='lobby'&&room.phase!=='opening' ? room.location.place : undefined, hint: you.role==='spy'&&room.phase!=='lobby'&&room.phase!=='opening' ? room.location.hint : undefined, hasVoted: room.votes.has(you.id) } : null;
  const turn = room.turnOrder[room.turnIndex];
  return { code:room.code, phase:room.phase, players, me, round:room.round, activeCount:players.filter(p=>p.active).length, currentTurn:turn||null, turnName:room.players.get(turn)?.name||null, turnIndex:room.turnIndex, turnCount:room.turnOrder.length, question:room.currentQuestion, targetId:room.targetId, timerEndsAt:room.timerEndsAt, votesIn:room.votes.size, eligibleVotes:room.voters.length, revealedVotes:room.revealedVotes||null, eliminatedId:room.eliminatedId||null, announcement:room.announcement||null, finalFour:room.finalFour||false, winner:room.winner||null, spyName:room.winner ? room.players.get(room.spyId)?.name : undefined, questions:room.questions||[], tieIds:room.tieIds||[], revision:room.revision };
}
function broadcast(room) { room.revision++; for(const [id,subs] of room.clients) { const payload=`data: ${JSON.stringify(publicState(room,id))}\n\n`; for(const res of [...subs]) { try { res.write(payload); } catch { subs.delete(res); } } } }
function transition(room, phase, duration=0) { clearTimeout(timers.get(room.code)); room.phase=phase; room.timerEndsAt=duration?Date.now()+duration:0; broadcast(room); if(duration) timers.set(room.code,setTimeout(()=>onTimeout(room),duration)); }
function resetRoom(room) { clearTimeout(timers.get(room.code)); room.phase='lobby'; room.round=1; room.spyId=null; room.location=null; room.turnOrder=[]; room.turnIndex=0; room.votes=new Map(); room.voters=[]; room.revealedVotes=null; room.winner=null; room.finalFour=false; room.announcement=null; room.questions=[]; room.history=[]; room.players.forEach(p=>{p.active=true;p.role=null;}); }
function beginQuestioning(room) { room.turnOrder=[...room.players.values()].filter(p=>p.active).map(p=>p.id); for(let i=room.turnOrder.length-1;i>0;i--){const j=rand(i+1);[room.turnOrder[i],room.turnOrder[j]]=[room.turnOrder[j],room.turnOrder[i]];} room.turnIndex=0; room.currentQuestion=null; room.targetId=null; room.votes=new Map(); room.voters=[]; room.revealedVotes=null; room.questions=room.location.qs.slice().sort(()=>rand(2)-1); transition(room,'question',45000); }
function beginVote(room, isRevote=false) { room.votes=new Map(); room.voters=isRevote?room.tieIds.filter(id=>room.players.get(id)?.active):[...room.players.values()].filter(p=>p.active).map(p=>p.id); room.revealedVotes=null; room.announcement=isRevote?'TIE — REVOTE':'WHO IS THE SPY?'; transition(room,isRevote?'revote':'vote',45000); }
function completeVote(room) { clearTimeout(timers.get(room.code)); room.timerEndsAt=0; const counts={}; for(const [voter,target] of room.votes) counts[target]=(counts[target]||0)+1; const max=Math.max(0,...Object.values(counts)); const tied=room.voters.filter(id=>(counts[id]||0)===max); room.revealedVotes={counts, ballotCount:room.votes.size}; broadcast(room); if(tied.length===1){setTimeout(()=>eliminate(room,tied[0]),2400);return;} if(room.phase==='vote') { room.tieIds=tied; room.announcement='TIE — REVOTE'; setTimeout(()=>beginVote(room,true),2600); } else { const pick=tied[rand(tied.length)]; room.announcement='THE HOTEL HAS DECIDED'; setTimeout(()=>eliminate(room,pick),2600); } }
function eliminate(room, id) { if(!room.players.get(id)?.active)return; const player=room.players.get(id); player.active=false; room.eliminatedId=id; room.revealedVotes=room.revealedVotes||{counts:{},ballotCount:room.votes.size}; if(id===room.spyId){ room.winner='civilians'; room.announcement='CIVILIANS WIN'; transition(room,'gameover');return; } if(room.finalFour){room.winner='spy';room.announcement='SPY WINS';transition(room,'gameover');return;} const count=[...room.players.values()].filter(p=>p.active).length; if(count===4){room.finalFour=true;room.announcement='FINAL FOUR';room.round++;transition(room,'intermission',4500);timers.set(room.code,setTimeout(()=>beginQuestioning(room),4500));return;} room.announcement='WRONG PERSON';room.round++; transition(room,'intermission',4500);timers.set(room.code,setTimeout(()=>beginQuestioning(room),4500)); }
function onTimeout(room) { if(room.phase==='question'){room.turnIndex++;room.currentQuestion=null;room.targetId=null;if(room.turnIndex>=room.turnOrder.length){beginVote(room);return;}transition(room,'question',45000);return;} if(room.phase==='vote'||room.phase==='revote') completeVote(room); }
function error(res,status,msg){res.writeHead(status,{'Content-Type':'application/json','Access-Control-Allow-Origin':'*'});res.end(JSON.stringify({error:msg}));}
function send(res,body,status=200){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store','Access-Control-Allow-Origin':'*'});res.end(JSON.stringify(body));}
function read(req){return new Promise((resolve,reject)=>{let s='';req.on('data',d=>{s+=d;if(s.length>16000)reject(Error('Request too large'));});req.on('end',()=>{try{resolve(JSON.parse(s||'{}'));}catch{reject(Error('Invalid JSON'));}});});}
function session(req){return req.headers['x-session']||'';}
const server=http.createServer(async(req,res)=>{
  const url=new URL(req.url,'http://localhost');
  if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,X-Session'});res.end();return;}
  if(url.pathname==='/api/health')return send(res,{ok:true,rooms:rooms.size});
  if(url.pathname==='/api/room'&&req.method==='POST'){
    let b;try{b=await read(req);}catch{return error(res,400,'Invalid request');}
    let c=code();while(rooms.has(c))c=code();const id=token();const name=String(b.name||'').trim().slice(0,18)||'Guest';const room={code:c,players:new Map(),clients:new Map(),hostId:id,phase:'lobby',round:1,spyId:null,location:null,turnOrder:[],turnIndex:0,votes:new Map(),voters:[],revision:0,questions:[],history:[]};room.players.set(id,{id,name,avatar:{category:'Man',variant:'01'},connected:true,active:true,role:null});rooms.set(c,room);return send(res,{code:c,session:id,state:publicState(room,id)});
  }
  const m=url.pathname.match(/^\/api\/room\/([A-Z0-9]+)(?:\/(events|action|join))?$/i);if(!m){const file=path.join(ROOT,url.pathname==='/'?'index.html':decodeURIComponent(url.pathname.slice(1)));if(file.startsWith(ROOT)&&fs.existsSync(file)&&fs.statSync(file).isFile()){res.writeHead(200,{'Content-Type':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html','Cache-Control':'no-cache'});fs.createReadStream(file).pipe(res);return;}return error(res,404,'Not found');}
  const room=rooms.get(m[1].toUpperCase());if(!room)return error(res,404,'Room not found');
  if(m[2]==='join'&&req.method==='POST'){let b;try{b=await read(req);}catch{return error(res,400,'Invalid request');}if(room.phase!=='lobby')return error(res,409,'This room has already started');if(room.players.size>=6)return error(res,409,'This room is full');const id=token();room.players.set(id,{id,name:String(b.name||'').trim().slice(0,18)||'Guest',avatar:{category:'Man',variant:String(room.players.size+1).padStart(2,'0')},connected:true,active:true,role:null});broadcast(room);return send(res,{code:room.code,session:id,state:publicState(room,id)});}
  const playerId=session(req)||(new URL(req.url,'http://localhost').searchParams.get('session')||'');const player=room.players.get(playerId);if(!player)return error(res,401,'Session not in room');
  if(m[2]==='events'&&req.method==='GET'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive','Access-Control-Allow-Origin':'*'});res.write(`data: ${JSON.stringify(publicState(room,playerId))}\n\n`);let set=room.clients.get(playerId);if(!set)room.clients.set(playerId,set=new Set());set.add(res);player.connected=true;broadcast(room);req.on('close',()=>{set.delete(res);player.connected=set.size>0;broadcast(room);});return;}
  if(m[2]==='action'&&req.method==='POST'){let b;try{b=await read(req);}catch{return error(res,400,'Invalid request');}const fail=(s,t)=>error(res,s,t);const active=[...room.players.values()].filter(p=>p.active);const isHost=room.hostId===playerId;
    if(b.type==='join'){return fail(409,'Room is already open to play.');}
    if(b.type==='avatar'){if(room.phase!=='lobby')return fail(409,'Avatar selection is closed');const categories=['Kid','Man','Woman','Old Man','Old Woman'];const category=categories.includes(b.category)?b.category:'Man';const variant=variants.includes(String(b.variant))?String(b.variant):'01';if([...room.players.values()].some(p=>p.id!==playerId&&p.avatar.category===category&&p.avatar.variant===variant))return fail(409,'That exact character is already taken. Choose another variant.');player.avatar={category,variant};}
    else if(b.type==='start'){if(!isHost)return fail(403,'Only the host can start');if(room.phase!=='lobby')return fail(409,'Game already started');if(active.length<5||active.length>6)return fail(409,'The game needs 5 or 6 players');room.location=locations[rand(locations.length)];const shuffled=active.slice();for(let i=shuffled.length-1;i>0;i--){const j=rand(i+1);[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]];}room.spyId=shuffled[0].id;for(const p of active)p.role=p.id===room.spyId?'spy':'civilian';transition(room,'opening',8000);timers.set(room.code,setTimeout(()=>{transition(room,'private',6000);timers.set(room.code,setTimeout(()=>{room.announcement='ROOM 401';transition(room,'room401',5000);timers.set(room.code,setTimeout(()=>beginQuestioning(room),5000));},6000));},8000));}
    else if(b.type==='question'){if(room.phase!=='question')return fail(409,'Question phase is closed');if(room.turnOrder[room.turnIndex]!==playerId)return fail(403,'It is not your turn');if(!room.questions.includes(b.question))return fail(400,'Choose a question from the list');const target=room.players.get(b.targetId);if(!target?.active||target.id===playerId)return fail(400,'Choose another active player');room.targetId=target.id;room.currentQuestion=String(b.question||'').slice(0,120);room.phase='answer';room.announcement=`${player.name} is asking ${target.name}`;room.timerEndsAt=Date.now()+25000;broadcast(room);timers.set(room.code,setTimeout(()=>{room.turnIndex++;room.targetId=null;room.currentQuestion=null;if(room.turnIndex>=room.turnOrder.length)beginVote(room);else transition(room,'question',45000);},25000));}
    else if(b.type==='answer'){if(room.phase!=='answer'||room.targetId!==playerId)return fail(403,'You are not being asked');room.history.push({round:room.round,asker:room.turnOrder[room.turnIndex],target:playerId,question:room.currentQuestion,answer:String(b.answer||'').slice(0,160)});room.turnIndex++;room.targetId=null;room.currentQuestion=null;if(room.turnIndex>=room.turnOrder.length)beginVote(room);else transition(room,'question',45000);}
    else if(b.type==='vote'){if(!['vote','revote'].includes(room.phase))return fail(409,'Voting is closed');if(!room.voters.includes(playerId))return fail(403,'You cannot vote in this ballot');if(room.votes.has(playerId))return fail(409,'Vote already submitted');const target=room.players.get(b.targetId);if(!target?.active||target.id===playerId)return fail(400,'Choose another active player');room.votes.set(playerId,target.id);broadcast(room);if(room.voters.every(id=>room.votes.has(id)))completeVote(room);}
    else if(b.type==='replay'){if(!isHost)return fail(403,'Only the host can replay');if(room.phase!=='gameover')return fail(409,'Game is still running');resetRoom(room);}
    else if(b.type==='leave'){room.players.delete(playerId);room.clients.delete(playerId);if(room.hostId===playerId)room.hostId=room.players.keys().next().value||null;if(room.players.size===0){rooms.delete(room.code);clearTimeout(timers.get(room.code));return send(res,{ok:true,left:true});}if(room.phase!=='lobby'&&room.phase!=='gameover'){if(playerId===room.spyId){room.winner='civilians';room.announcement='CIVILIANS WIN';transition(room,'gameover');}else if(room.phase==='vote'||room.phase==='revote'){room.voters=room.voters.filter(id=>id!==playerId);if(room.voters.every(id=>room.votes.has(id)))completeVote(room);else broadcast(room);}else{room.turnOrder=room.turnOrder.filter(id=>id!==playerId);if(room.targetId===playerId){room.turnIndex++;room.targetId=null;room.currentQuestion=null;if(room.turnIndex>=room.turnOrder.length)beginVote(room);else transition(room,'question',45000);}else{if(room.turnIndex>=room.turnOrder.length)room.turnIndex=0;broadcast(room);}}}else broadcast(room);return send(res,{ok:true,left:true});}
    else return fail(400,'Unknown action');
    return send(res,{ok:true,state:publicState(room,playerId)});
  }
  return error(res,404,'Not found');
});
server.listen(PORT,'0.0.0.0',()=>console.log(`SPY: LAST FOUR listening on ${PORT}`));
